### ISSUE TITLE
NB 18: unnecessarily loading and printing too much data -> bad performance

### ISSUE THREAD

**Issue by cknoll** [Cognonto/CWPK#5]
Printing every line of [kbpedia_reference_concepts.owl](https://raw.githubusercontent.com/Cognonto/CWPK/master/sandbox/builds/ontologies/kbpedia_reference_concepts.owl) is imho not necessary. Most users will never read 70MB of XML. However all users are affected by the accompanying  performance loss.

**Comment by mkbergman** [comment]
As noted on the pull request, this may indeed be a good decision for many/most use cases. I am reluctant, however, to hardwire any limits into the code. You are, of course, free to make changes to local versions.
