### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by cknoll** [Cognonto/CWPK#8]
I currently compile a heavily condensed version of this installment series (one single notebook). I mainly do this for myself and maybe for my students. However, I would like to share that work as well with others. Currently I am unsure whether this is allowed, because "my work" basically consist of copying selected code, text and images from the original work, with some minor editing (such as paths).

For me this seems like a typical use case for some Creative Common License. It would be great if such a permissive license would be added to this repo as it would allow to publish derivative works such as mine.

I think this would also contribute to the visibility of the original work and its producer.

**Comment by mkbergman** [comment]
License now provided.
